theme: jekyll-theme-architect

title: [Java Servlet Specification]
description: [Collaboration home for Java Servlet Specification]

# sidebar links url
links:
  source: https://github.com/javaee/servlet-spec
  #download: https://github.com/javaee/servlet-spec/tree/gh-pages
  mailinglist: https://javaee.groups.io/g/servlet-spec/topics
  #javadocs:
  #docs:
  #faq:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed


